"use client";

import { Crest } from "./Crest";
import { formatNGN } from "@/lib/money";
import { formatDateTime, fullName, methodLabel } from "@/lib/format";

type ReceiptData = {
  receiptNumber: string;
  issuedAt: Date;
  tenant: { name: string; city: string; country: string; motto: string | null };
  payment: {
    reference: string;
    amountKobo: number;
    method: string;
    paidAt: Date;
    notes: string | null;
    invoice: { invoiceNumber: string; session: string };
    student: {
      firstName: string;
      lastName: string;
      otherNames: string | null;
      matricNumber: string;
      programme: string;
    };
  };
};

export function ReceiptView({ data }: { data: ReceiptData }) {
  const { payment } = data;
  return (
    <div className="mx-auto max-w-2xl">
      <div className="card print:shadow-none p-8">
        <div className="flex items-start justify-between gap-4 border-b border-forest-100 pb-6 dark:border-forest-800">
          <div className="flex items-center gap-3">
            <Crest className="h-12 w-12" />
            <div>
              <div className="font-display text-2xl">{data.tenant.name}</div>
              <div className="text-sm text-forest-600">
                {data.tenant.city}, {data.tenant.country}
              </div>
              {data.tenant.motto && (
                <div className="text-xs italic text-forest-500">{data.tenant.motto}</div>
              )}
            </div>
          </div>
          <div className="text-right">
            <div className="text-xs uppercase tracking-widest text-gold-600">Official receipt</div>
            <div className="font-mono text-lg">{data.receiptNumber}</div>
          </div>
        </div>

        <dl className="mt-6 grid gap-4 sm:grid-cols-2 text-sm">
          <div>
            <dt className="text-xs uppercase text-forest-500">Received from</dt>
            <dd className="font-medium">{fullName(payment.student)}</dd>
            <dd className="text-forest-600">{payment.student.matricNumber}</dd>
            <dd className="text-forest-600">{payment.student.programme}</dd>
          </div>
          <div>
            <dt className="text-xs uppercase text-forest-500">Against invoice</dt>
            <dd className="font-medium">{payment.invoice.invoiceNumber}</dd>
            <dd className="text-forest-600">{payment.invoice.session} session</dd>
          </div>
          <div>
            <dt className="text-xs uppercase text-forest-500">Amount</dt>
            <dd className="font-display text-3xl">{formatNGN(payment.amountKobo)}</dd>
          </div>
          <div>
            <dt className="text-xs uppercase text-forest-500">Method / reference</dt>
            <dd>{methodLabel(payment.method)}</dd>
            <dd className="font-mono text-xs">{payment.reference}</dd>
            <dd>{formatDateTime(payment.paidAt)}</dd>
          </div>
        </dl>

        <p className="mt-8 text-xs text-forest-500">
          This is a demonstration receipt generated by CampusFlow. No live payment processor was
          contacted. Keep this number for bursary enquiries.
        </p>
        <button
          type="button"
          onClick={() => window.print()}
          className="btn-secondary mt-6 print:hidden"
        >
          Print
        </button>
      </div>
    </div>
  );
}
